name: configs
on:
  push:
  schedule:
    - cron:  '0 12 * * *'
jobs:
  system:
    strategy:
      fail-fast: false
      matrix:
        machine: [xps, vultr]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
        fetch-depth: 0
    - name: Install nix
      uses: cachix/install-nix-action@v12
      with:
        install_url: https://github.com/numtide/nix-flakes-installer/releases/download/nix-3.0pre20200820_4d77513/install
        nix_path: nixpkgs=channel:nixos-unstable
        extra_nix_config: |
          experimental-features = nix-command flakes
    - name: Install cachix
      uses: cachix/cachix-action@v8
      with:
        name: nix-cfg
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - name: Build system config
      run: nix build .#nixosConfigurations.${{ matrix.machine }}.config.system.build.toplevel
